
import {useEffect,useMemo,useState} from "react";
import {Activity,AlertCircle,Bell,CalendarDays,CheckCircle2,ChevronDown,Eye,LayoutDashboard,LogOut,Mail,Menu,MessageSquare,Phone,RefreshCw,Search,ShieldCheck,Star,Stethoscope,UserRound,X} from "lucide-react";

const API=(import.meta.env.VITE_API_URL||"http://localhost:5000").replace(/\/$/,"");
const TOKEN="suguna_admin_token";
const statuses=["New","Contacted","Confirmed","Completed","Cancelled"];

async function api(path,opt={},token=""){
  const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});
  const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={message:t}}
  if(!r.ok)throw Error(d.message||d.error||`Request failed (${r.status})`);
  return d;
}
async function first(paths,token){let e;for(const p of paths)try{return await api(p,{},token)}catch(x){e=x}throw e}
const arr=(d,k)=>Array.isArray(d)?d:(Array.isArray(d?.[k])?d[k]:Array.isArray(d?.data)?d.data:[]);
const ap=x=>({...x,id:x._id||x.id,patientName:x.patientName||x.name||x.fullName||"Unknown patient",phone:x.phone||x.phoneNumber||"",email:x.email||"",department:x.department||x.speciality||"General Medicine",date:x.date||x.appointmentDate||"",time:x.time||x.appointmentTime||"",status:x.status||"New",message:x.message||x.notes||"",assignedDoctor:x.assignedDoctor||x.doctor||"",adminNotes:x.adminNotes||""});
const en=x=>({...x,id:x._id||x.id,name:x.name||x.fullName||"Patient",phone:x.phone||x.phoneNumber||"",email:x.email||"",subject:x.subject||x.department||"Patient enquiry",message:x.message||x.content||""});
const rv=x=>({...x,id:x._id||x.id,name:x.name||x.patientName||"Patient",rating:Number(x.rating||0),message:x.message||x.review||x.comment||"",status:x.status||(x.approved?"Approved":"Pending")});
const date=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})};

function Login({done}){
 const[key,setKey]=useState(""),[busy,setBusy]=useState(false),[err,setErr]=useState("");
 async function submit(e){e.preventDefault();if(!key.trim())return setErr("Enter your admin key.");setBusy(true);setErr("");try{const d=await api("/api/admin/login",{method:"POST",body:JSON.stringify({adminKey:key.trim(),key:key.trim()})});const t=d.token||d.accessToken||d.jwt;if(!t)throw Error("No login token returned.");localStorage.setItem(TOKEN,t);done(t)}catch(x){setErr(x.message)}finally{setBusy(false)}}
 return <div className="login"><div className="orb a"/><div className="orb b"/><div className="login-card">
  <div className="brand"><b>S</b><div><strong>SUGUNA</strong><small>MULTISPECIALITY</small></div></div>
  <span className="pill"><ShieldCheck size={14}/> ADMIN PORTAL</span><h1>Welcome back.</h1><p>Manage appointments, enquiries and patient reviews from one secure workspace.</p>
  <form onSubmit={submit}><label>Admin Key</label><div className="input"><ShieldCheck size={17}/><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Enter admin key"/></div>{err&&<div className="error"><AlertCircle size={15}/>{err}</div>}<button className="primary full" disabled={busy}>{busy?<><RefreshCw className="spin" size={16}/> Signing in...</>:<>Sign in →</>}</button></form>
  <div className="secure"><ShieldCheck size={13}/> Secure hospital administration</div><footer>Suguna Multispeciality · Hospital Administration</footer>
 </div></div>
}

function App(){const[t,setT]=useState(localStorage.getItem(TOKEN));return t?<Dashboard token={t} logout={()=>{localStorage.removeItem(TOKEN);setT(null)}}/>:<Login done={setT}/>}

function Dashboard({token,logout}){
 const[tab,setTab]=useState("overview"),[apps,setApps]=useState([]),[ens,setEns]=useState([]),[revs,setRevs]=useState([]),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState(null),[search,setSearch]=useState(""),[mobile,setMobile]=useState(false),[notice,setNotice]=useState("");
 async function load(silent=false){silent?setRefresh(true):setLoading(true);setError("");try{const[a,e,r]=await Promise.all([first(["/api/appointments","/api/admin/appointments"],token),first(["/api/enquiries","/api/admin/enquiries"],token).catch(()=>({})),first(["/api/reviews","/api/admin/reviews"],token).catch(()=>({}))]);setApps(arr(a,"appointments").map(ap));setEns(arr(e,"enquiries").map(en));setRevs(arr(r,"reviews").map(rv))}catch(x){setError(x.message)}finally{setLoading(false);setRefresh(false)}}
 useEffect(()=>{load();const id=setInterval(()=>load(true),15000);return()=>clearInterval(id)},[]);
 const stats=useMemo(()=>({a:apps.length,c:apps.filter(x=>x.status==="Confirmed").length,e:ens.length,r:revs.filter(x=>!["Approved","Published"].includes(String(x.status))).length}),[apps,ens,revs]);
 async function status(id,s){try{let ok=false;for(const p of [`/api/appointments/${id}/status`,`/api/appointments/${id}`])try{await api(p,{method:"PATCH",body:JSON.stringify({status:s})},token);ok=true;break}catch{}if(!ok)throw Error("Status update failed");setApps(q=>q.map(x=>x.id===id?{...x,status:s}:x));setNotice("Appointment status updated.");setTimeout(()=>setNotice(""),2200)}catch(x){setError(x.message)}}
 const filtered=apps.filter(x=>!search||[x.patientName,x.phone,x.department,x.status,x.assignedDoctor].join(" ").toLowerCase().includes(search.toLowerCase()));
 const nav=x=>{setTab(x);setMobile(false);setSearch("")};
 return <div className="shell"><aside className={mobile?"side open":"side"}><div className="sidebrand"><b>S</b><div><strong>SUGUNA</strong><small>MULTISPECIALITY</small></div></div><div className="label">HOSPITAL ADMIN</div><nav>{[["overview","Overview",LayoutDashboard,""],["appointments","Appointments",CalendarDays,stats.a],["enquiries","Enquiries",MessageSquare,stats.e],["reviews","Reviews",Star,stats.r]].map(([id,n,I,c])=><button className={tab===id?"active":""} onClick={()=>nav(id)} key={id}><I size={18}/>{n}<em>{c}</em></button>)}</nav><div className="sidebottom"><div className="live"><i/> API connected<small>Live data</small></div><button onClick={logout}><LogOut size={16}/> Logout</button></div></aside>
 <main className="main"><header><div className="headleft"><button className="hamb" onClick={()=>setMobile(!mobile)}><Menu/></button><div><small>SUGUNA MULTISPECIALITY</small><h2>{tab==="overview"?"Hospital overview":tab[0].toUpperCase()+tab.slice(1)}</h2></div></div><div className="headright"><button className="icon" onClick={()=>load(true)}><RefreshCw className={refresh?"spin":""} size={17}/></button><button className="icon bell"><Bell size={17}/>{stats.a>0&&<i/>}</button><div className="admin"><b>AD</b><span>Admin<small>Administrator</small></span><ChevronDown size={14}/></div></div></header>
 {error&&<div className="banner error"><AlertCircle size={16}/>{error}<button onClick={()=>setError("")}><X size={15}/></button></div>}{notice&&<div className="banner ok"><CheckCircle2 size={16}/>{notice}</div>}
 {tab==="overview"?<Overview stats={stats} apps={apps} loading={loading} open={()=>nav("appointments")} select={setSelected}/>:tab==="appointments"?<Appointments list={filtered} search={search} setSearch={setSearch} loading={loading} select={setSelected} status={status}/>:tab==="enquiries"?<Cards title="Enquiries" kicker="PATIENT COMMUNICATION" text="Patient messages received through the website." list={ens} loading={loading} kind="enquiry" select={setSelected}/>:<Cards title="Reviews" kicker="PATIENT FEEDBACK" text="Review patient feedback before publishing it." list={revs} loading={loading} kind="review" select={setSelected}/>}
 </main>{selected&&<Modal item={selected} close={()=>setSelected(null)} status={status}/>}</div>
}

function Overview({stats,apps,loading,open,select}){const recent=apps.slice().sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0)).slice(0,6);return <div className="content"><section className="welcome"><div><span><Activity size={14}/> LIVE HOSPITAL DATA</span><h1>Good day, Admin.</h1><p>Monitor patient bookings and hospital enquiries from one professional dashboard.</p></div><button className="primary" onClick={open}><CalendarDays size={16}/> Manage appointments</button></section><div className="stats">{[[CalendarDays,"Total appointments",stats.a,"blue"],[CheckCircle2,"Confirmed bookings",stats.c,"green"],[MessageSquare,"Patient enquiries",stats.e,"purple"],[Star,"Pending reviews",stats.r,"gold"]].map(([I,n,v,t])=><div className="stat" key={n}><div className={"staticon "+t}><I size={19}/></div><div><b>{v}</b><span>{n}</span></div></div>)}</div><div className="twocol"><section className="panel"><div className="panelhead"><div><h3>Recent appointments</h3><p>Latest patient booking activity</p></div><button onClick={open}>View all →</button></div>{loading?<Skeleton/>:recent.length?<Table list={recent} select={select} compact/>:<Empty icon={CalendarDays} text="No appointments yet."/>}</section><section className="panel glance"><div className="panelhead"><div><h3>Today at a glance</h3><p>Operational summary</p></div></div>{[["New bookings","New"],["Contacted","Contacted"],["Confirmed","Confirmed"],["Completed","Completed"]].map(([n,s])=><div key={s}><span>{n}</span><b>{apps.filter(x=>x.status===s).length}</b></div>)}</section></div></div>}

function Appointments({list,search,setSearch,loading,select,status}){return <div className="content"><div className="title"><span>PATIENT BOOKINGS</span><h1>Appointments</h1><p>Review, contact and manage every patient booking.</p></div><div className="toolbar"><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search patient, phone, department..."/></div><small>{list.length} records</small></div><section className="panel">{loading?<Skeleton/>:list.length?<Table list={list} select={select} status={status}/>:<Empty icon={CalendarDays} text="No matching appointments found."/>}</section></div>}
function Table({list,select,status,compact}){return <div className="scroll"><table><thead><tr><th>Patient</th><th>Department</th><th>Date & time</th><th>Status</th><th/></tr></thead><tbody>{list.map(a=><tr key={a.id}><td><div className="patient"><b>{a.patientName[0]?.toUpperCase()}</b><span><strong>{a.patientName}</strong><small>{a.phone||a.email||"No contact"}</small></span></div></td><td><strong>{a.department}</strong>{!compact&&a.assignedDoctor&&<small>Dr. {a.assignedDoctor}</small>}</td><td><strong>{date(a.date||a.createdAt)}</strong><small>{a.time||"Time not specified"}</small></td><td><select className={"status "+a.status.toLowerCase()} value={a.status} onChange={e=>status?.(a.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td><button className="view" onClick={()=>select(a)}><Eye size={14}/> View</button></td></tr>)}</tbody></table></div>}
function Cards({title,kicker,text,list,loading,kind,select}){return <div className="content"><div className="title"><span>{kicker}</span><h1>{title}</h1><p>{text}</p></div>{loading?<div className="cards">{[1,2,3].map(i=><div className="panel loading" key={i}/>)}</div>:<div className="cards">{list.length?list.map(x=>kind==="enquiry"?<div className="card" key={x.id} onClick={()=>select(x)}><div className="cardtop"><b><MessageSquare size={16}/></b><small>{date(x.createdAt)}</small></div><h3>{x.subject}</h3><strong>{x.name}</strong><p>{x.message||"No message provided."}</p><div className="meta">{x.phone&&<span><Phone size={13}/>{x.phone}</span>}{x.email&&<span><Mail size={13}/>{x.email}</span>}</div></div>:<div className="card" key={x.id} onClick={()=>select(x)}><div className="reviewtop"><b>{x.name[0]?.toUpperCase()}</b><span><strong>{x.name}</strong><small>{date(x.createdAt)}</small></span><em>{x.status}</em></div><div className="stars">{[1,2,3,4,5].map(i=><Star key={i} size={15} fill={i<=x.rating?"currentColor":"none"}/>)}</div><p>{x.message||"No review text."}</p></div>):<div className="panel"><Empty icon={kind==="review"?Star:MessageSquare} text={`No ${title.toLowerCase()} found.`}/></div>}</div>}</div>}
function Modal({item,close,status}){const isAp=!!item.department||!!item.patientName;return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalhead"><div><span>RECORD DETAILS</span><h2>{item.patientName||item.name||"Patient record"}</h2></div><button onClick={close}><X/></button></div><div className="details">{item.phone&&<D n="Phone"><Phone/>{item.phone}</D>}{item.email&&<D n="Email"><Mail/>{item.email}</D>}{item.department&&<D n="Department"><Stethoscope/>{item.department}</D>}{(item.date||item.createdAt)&&<D n="Date"><CalendarDays/>{date(item.date||item.createdAt)}</D>}{item.time&&<D n="Time"><span>{item.time}</span></D>}{item.assignedDoctor&&<D n="Assigned doctor"><UserRound/>{item.assignedDoctor}</D>}{item.message&&<div className="detailfull"><small>Message</small><p>{item.message}</p></div>}{item.adminNotes&&<div className="detailfull"><small>Admin notes</small><p>{item.adminNotes}</p></div>}</div>{isAp&&item.id&&<div className="modalfoot"><label>Status<select className={"status "+String(item.status).toLowerCase()} value={item.status} onChange={e=>status(item.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><button onClick={close}>Close</button></div>}</div></div>}
function D({n,children}){return <div><small>{n}</small><strong>{children}</strong></div>}
function Skeleton(){return <div className="skeleton">{[1,2,3,4].map(i=><i key={i}/>)}</div>}
function Empty({icon:I,text}){return <div className="empty"><I size={28}/><strong>{text}</strong><span>New activity will appear here automatically.</span></div>}
export default App;
